#!/bin/bash
#svn
#yum -y install svn
#cd /tmp/
#svn checkout https://github.com/zzzmax/sumus.git
cd /tmp/sumus.git/trunk/
tar -zxvf /tmp/sumus.git/trunk/gm*.tgz
cd /opt/
mkdir sumus
cd /opt/sumus/
yum install -y /tmp/sumus.git/trunk/server/sumus-*.rpm
cp /tmp/sumus.git/trunk/shell/linux/* /opt/sumus
yes | cp /tmp/sumus.git/trunk/genesis_block.txt /etc/sumus
chmod +x shell.gm
#add firewald rules
firewall-cmd  --permanent --add-rich-rule='rule family="ipv4" port port=4010 protocol="tcp" accept'
firewall-cmd  --permanent --add-rich-rule='rule family="ipv4" port port=50555 protocol="tcp" accept'
systemctl restart firewalld
rm -rf /tmp/sumus.git/



