#!/bin/bash
#svn
yum -y install svn
cd /tmp/
svn checkout https://github.com/Goldmint/sumus/trunk
#lib
cd trunk
tar xzvf lib_boost.166.tar.gz -C /usr/local/lib
echo "/usr/local/lib" >> /etc/ld.so.conf
ldconfig
#copy sumus 
cp sumus.service /etc/systemd/system
cd /opt/
mkdir sumus
cd /opt/sumus/
cp /tmp/trunk/sumus_start.sh /opt/sumus/
chmod +x sumus_start.sh
chmod +x ./shell-debug
mkdir wallets
cp -Rnv /tmp/trunk/sumus.tar/* /tmp/trunk/sumus.tar/.[a-zA-Z0-9]* /opt/sumus
#add sumus service
systemctl daemon-reload
systemctl start sumus.service
systemctl enable sumus.service
#add firewald rules
firewall-cmd  --permanent --add-rich-rule='rule family="ipv4" port port=4010 protocol="tcp" accept'
firewall-cmd  --permanent --add-rich-rule='rule family="ipv4" port port=50805 protocol="tcp" accept'
systemctl restart firewalld
#make swap 
dd if=/dev/zero of=/swap bs=1M count=4096
mkswap /swap
chmod 600 /swap
swapon /swap
echo "/swap swap swap defaults 0 0" >> /etc/fstab



